#!/bin/sh

set -e
#set -x

#########################
# var
#########################

if [ ! -d /var/lib/solr ]; then
  mkdir /var/lib/solr/
fi
if [ ! -d /var/lib/solr/xwiki ]; then
  mkdir /var/lib/solr/xwiki/
fi
