#!/bin/sh

set -e
#set -x

#########################
# Restart XWiki
#########################

# Restart XWiki service (only if it's active)
if systemctl -q is-active xwiki.service
then
 systemctl xwiki restart
fi
