packages:
  - xwiki-platform-core/xwiki-platform-blocknote/xwiki-platform-blocknote-webjar/src/main/node/
  - xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar/src/main/node/
  - xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-webjar/src/main/node/
  - xwiki-platform-node/src/main/node/api
  - xwiki-platform-node/src/main/node/core/attachments/attachments-default
  - xwiki-platform-node/src/main/node/core/authentication/authentication-api
  - xwiki-platform-node/src/main/node/core/backends/backend-api
  - xwiki-platform-node/src/main/node/core/document/document-api
  - xwiki-platform-node/src/main/node/ds/api
  - xwiki-platform-node/src/main/node/editors/blocknote-headless
  - xwiki-platform-node/src/main/node/editors/blocknote-react
  - xwiki-platform-node/src/main/node/core/link-suggest/link-suggest-api
  - xwiki-platform-node/src/main/node/dev/config
  - xwiki-platform-node/src/main/node/core/configuration/configuration-api
  - xwiki-platform-node/src/main/node/core/attachments/attachments-api
  - xwiki-platform-node/src/main/node/core/navigation-tree/navigation-tree-api
  - xwiki-platform-node/src/main/node/core/collaboration/collaboration-api
  - xwiki-platform-node/src/main/node/core/icons
  - xwiki-platform-node/src/main/node/core/uniast/uniast-api
  - xwiki-platform-node/src/main/node/core/uniast/uniast-markdown
  - xwiki-platform-node/src/main/node/core/model/model-api
  - xwiki-platform-node/src/main/node/core/model/model-reference/model-reference-api
  - xwiki-platform-node/src/main/node/core/model/model-remote-url/model-remote-url-api
  - xwiki-platform-node/src/main/node/core/fn-utils
  - xwiki-platform-node/src/main/node

catalog:
  '@blocknote/core': 0.31.3
  '@blocknote/mantine': 0.31.3
  '@blocknote/react': 0.35.0
  '@mantine/core': 8.1.1
  '@mantine/hooks': 8.3.3
  '@playwright/experimental-ct-react': 1.55.1
  '@tsconfig/node22': 22.0.2
  '@types/jsdom': 27.0.0
  '@types/lodash-es': 4.17.12
  '@types/mdast': 4.0.4
  '@types/node': 22.18.8
  '@types/react': 19.2.0
  '@types/react-dom': 19.2.0
  '@vitejs/plugin-react': 5.0.1
  '@vitejs/plugin-vue': 6.0.1
  '@vitest/eslint-plugin': 1.3.4
  '@vue/eslint-config-prettier': 10.2.0
  '@vue/eslint-config-typescript': 14.6.0
  '@vue/test-utils': 2.4.6
  '@vue/tsconfig': 0.7.0
  bootstrap-icons: 1.13.1
  dompurify: 3.2.6
  eslint: 9.36.0
  eslint-plugin-vue: 10.5.0
  eventemitter3: 5.0.1
  fast-xml-parser: 5.3.0
  flush-promises: 1.0.2
  i18next: 25.5.3
  inversify: 7.5.2
  jiti: 2.6.0
  jquery: 3.7.1
  jsdom: 27.0.0
  lodash-es: 4.17.21
  lz-string: 1.5.0
  mdast-util-gfm-strikethrough: 2.0.0
  mdast-util-gfm-table: 2.0.0
  mdast-util-gfm-task-list-item: 2.0.0
  micromark-extension-gfm-strikethrough: 2.1.0
  micromark-extension-gfm-table: 2.1.1
  micromark-extension-gfm-task-list-item: 2.1.0
  npm-run-all2: 8.0.4
  pinia: 3.0.2
  postcss: 8.5.6
  postcss-preset-mantine: 1.18.0
  postcss-simple-vars: 7.0.1
  react: 19.1.0
  react-dom: 19.1.0
  react-i18next: 16.0.0
  react-icons: 5.5.0
  reflect-metadata: 0.2.2
  remark-parse: 11.0.0
  rimraf: 6.0.1
  sinon: 21.0.0
  tippy.js: 6.3.7
  typescript: 5.9.3
  u-node: 0.0.2
  unified: 11.0.5
  utility-types: 3.11.0
  vite: 7.1.7
  vitest: 3.2.4
  vitest-mock-extended: 3.1.0
  vue: 3.5.22
  vue-i18n: 11.1.12
  vue-router: 4.5.1
  vue-tippy: 6.7.1
  vue-tsc: 3.0.6
  vue3-touch-events: 5.0.13
  vuedraggable: 4.1.0
  yjs: 13.6.27
  nx: 21.6.4
  vite-plugin-css-injected-by-js: 3.5.2
  vite-plugin-dts: 4.5.4

catalogMode: strict

cleanupUnusedCatalogs: true
