#!/bin/sh

set -e
#set -x

#########################
# Rights
#########################

## Make sure Tomcat is able to write in the data folder
if [ ! 'tomcat8' = `stat -c '%U' /var/lib/xwiki/data` ]; then
  chown -R tomcat8:tomcat8 /var/lib/xwiki/data
fi
