/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.xwiki.chart.test.po;

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.xwiki.test.ui.po.BaseElement;

/**
 * Page object used to interact with a chart generated by the chart macro.
 *
 * @version $Id$
 * @since 18.9.0RC1
 * @since 18.4.7
 * @since 17.10.14
 * @since 16.10.20
 */
public class ChartElement extends BaseElement
{
    /**
     * The image of the chart.
     */
    private final WebElement image;

    /**
     * Creates a new instance that can be used to interact with the chart represented by the given image.
     *
     * @param image the image of the chart
     */
    public ChartElement(WebElement image)
    {
        this.image = image;
    }

    /**
     * @return the charts displayed in the content of the currently viewed page, in document order
     */
    public static List<ChartElement> getChartsInPageContent()
    {
        return getUtil().getDriver().findElementsWithoutWaiting(By.cssSelector("#xwikicontent img[src*='/chart/']"))
            .stream().map(ChartElement::new).toList();
    }

    /**
     * @return the title of the chart, as specified by the {@code title} parameter of the chart macro
     */
    public String getTitle()
    {
        return this.image.getDomAttribute("alt");
    }
}
