#!/bin/sh

set -e
#set -x

if [ ! -d /var/lib/xwiki/ ]; then
  mkdir /var/lib/xwiki/
fi
if [ ! -d /var/lib/xwiki/solr/ ]; then
  mkdir /var/lib/xwiki/solr/
fi

# Make the default solr user ("solr") owner of the data folder
if id "solr" >/dev/null 2>&1; then
  chown -R solr:solr /var/lib/xwiki/solr/events/
else
  echo "No user with name 'solr' could be found. Please make the user which runs Solr the owner of the folder /var/lib/xwiki/solr/events"
fi
