#!/bin/sh

set -e
#set -x

#########################
# Restart Tomcat
#########################

# Restart tomcat9 service (only if it's active)
if ( systemctl -q is-active tomcat9.service || systemctl -q is-enabled tomcat9.service )
then
  deb-systemd-invoke restart tomcat9.service
fi
