#!/bin/sh

set -e
#set -x

#########################
# Configuration
#########################

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/postinst.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.mysql

  extrasql=" CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"

  dbc_generate_include='template:/etc/xwiki/hibernate.cfg.xml'
  dbc_generate_include_perms='644'
  dbc_generate_include_args='-U -o template_infile=/usr/share/xwiki/templates/mariadb/hibernate.cfg.xml'

  dbc_go xwiki $@

  # Substitute db credentials with proper XML escaping.
  # The template uses ##XWIKI_DBUSER## and ##XWIKI_DBPASS## as unique placeholders so
  # that dbconfig-common does not perform unescaped substitution (which would break XML).
  if [ -f /etc/xwiki/hibernate.cfg.xml ]; then
    _xwiki_xml_escape() { printf '%s' "$1" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g'; }
    XWIKI_DBUSER=$(_xwiki_xml_escape "${dbc_dbuser:-}") \
    XWIKI_DBPASS=$(_xwiki_xml_escape "${dbc_dbpass:-}") \
    awk 'BEGIN {
           u = ENVIRON["XWIKI_DBUSER"]; un = length("##XWIKI_DBUSER##")
           p = ENVIRON["XWIKI_DBPASS"]; pn = length("##XWIKI_DBPASS##")
         }
         {
           while ((i = index($0, "##XWIKI_DBUSER##")) > 0) $0 = substr($0,1,i-1) u substr($0,i+un)
           while ((i = index($0, "##XWIKI_DBPASS##")) > 0) $0 = substr($0,1,i-1) p substr($0,i+pn)
           print
         }' \
      /etc/xwiki/hibernate.cfg.xml > /etc/xwiki/hibernate.cfg.xml.tmp \
    && mv /etc/xwiki/hibernate.cfg.xml.tmp /etc/xwiki/hibernate.cfg.xml
  fi

  # if they don't want our help, quit
  if [ "$dbc_install" != "true" ]; then exit 0; fi

  # find out if we're upgrading/reinstalling
  if [ "$dbc_oldversion" ]; then
    # read that little crumb left in config if we're reconfiguring
    db_get $dbc_package/internal/reconfiguring && reconfiguring="$RET"
    # and set it back to false
    db_reset $dbc_package/internal/reconfiguring
    # if not, we're definitely upgrading
    if [ "$reconfiguring" = "false" ]; then
        upgrading="yes"
    else
        db_get $dbc_package/dbconfig-reinstall && reinstall=$RET
        db_reset $dbc_package/dbconfig-reinstall
        # if they've said they don't want to reinstall stuff...
        if [ "$reinstall" = "false" ]; then exit 0; fi
    fi
  fi

  # don't perform the following block of code during upgrades
  if [ ! "$upgrading" ]; then
    # Allow creating new wikis (so new databases)
    # TODO: ask it in an install step

    # Get the host
    if [ ! "${dbc_dballow:-}" ]; then
        if [ ! "${dbc_dbserver:-}" ] || [ "$dbc_dbserver" = "localhost" ]; then
            l_dballow=localhost
        else
            l_dballow=`hostname`
        fi
    else
        l_dballow="$dbc_dballow"
    fi

    echo "allow $dbc_dbuser user to create new databases"
    dbc_mysql_exec_command "GRANT ALL PRIVILEGES ON *.* to $dbc_dbuser@'$l_dballow'"
  fi
fi
