/**
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
import { toCristalEntityReference } from "../reference/XWikiEntityReference";
import { Container, injectable } from "inversify";
import type { XWikiEntityReference } from "../reference/XWikiEntityReference";
import type { EntityReference } from "@xwiki/platform-model-api";
import type { RemoteURLParser } from "@xwiki/platform-model-remote-url-api";

// Matches the path of a document or attachment URL generated by XWiki.Document#getURL()/
// XWiki.Attachment#getURL(), e.g. "/bin/view/Space1/Space2/Page" or, for a subwiki,
// "/wiki/subwiki/bin/download/Space/Page/file.png".
const URL_PATH_REGEXP = /^(?:\/wiki\/([^/]+))?\/bin\/([^/]+)\/(.*)$/;

@injectable("Singleton")
export class XWikiRemoteURLParser implements RemoteURLParser {
  public static bind(container: Container): void {
    container
      .bind("RemoteURLParser")
      .to(XWikiRemoteURLParser)
      .inSingletonScope()
      .whenNamed("XWiki");
  }

  public parse(url: string): EntityReference | undefined {
    const path = this.getPathAfterContext(url);
    if (path === undefined) {
      return undefined;
    }

    const match = URL_PATH_REGEXP.exec(path);
    if (!match) {
      return undefined;
    }

    const [, wikiSegment, action, remainder] = match;
    const wikiName = wikiSegment
      ? decodeURIComponent(wikiSegment)
      : XWiki.currentWiki;

    const reference =
      action === "download"
        ? this.parseAttachment(wikiName, remainder)
        : this.parseDocument(wikiName, remainder);

    return toCristalEntityReference(reference);
  }

  private getPathAfterContext(url: string): string | undefined {
    let pathname: string;
    try {
      pathname = new URL(url, window.location.origin).pathname;
    } catch {
      return undefined;
    }

    if (!pathname.startsWith(XWiki.contextPath)) {
      return undefined;
    }

    return pathname.slice(XWiki.contextPath.length);
  }

  private parseDocument(
    wikiName: string,
    remainder: string,
  ): XWikiEntityReference | undefined {
    const segments = this.splitSegments(remainder);
    const endsWithSlash = remainder.endsWith("/");

    const spaceNames = endsWithSlash ? segments : segments.slice(0, -1);
    const pageName = endsWithSlash ? "WebHome" : segments[segments.length - 1];

    if (spaceNames.length === 0 || !pageName) {
      return undefined;
    }

    return this.buildDocumentReference(wikiName, spaceNames, pageName);
  }

  private parseAttachment(
    wikiName: string,
    remainder: string,
  ): XWikiEntityReference | undefined {
    const segments = this.splitSegments(remainder);
    if (segments.length < 2) {
      return undefined;
    }

    const filename = segments[segments.length - 1];
    const pageName = segments[segments.length - 2];
    const spaceNames = segments.slice(0, -2);

    if (spaceNames.length === 0) {
      return undefined;
    }

    const documentReference = this.buildDocumentReference(
      wikiName,
      spaceNames,
      pageName,
    );

    return new XWiki.EntityReference(
      filename,
      XWiki.EntityType.ATTACHMENT,
      documentReference,
    );
  }

  private buildDocumentReference(
    wikiName: string,
    spaceNames: string[],
    pageName: string,
  ): XWikiEntityReference {
    const wikiReference = new XWiki.EntityReference(
      wikiName,
      XWiki.EntityType.WIKI,
    );

    const spaceReference = spaceNames.reduce(
      (parent: XWikiEntityReference, name) =>
        new XWiki.EntityReference(name, XWiki.EntityType.SPACE, parent),
      wikiReference,
    );

    return new XWiki.EntityReference(
      pageName,
      XWiki.EntityType.DOCUMENT,
      spaceReference,
    );
  }

  private splitSegments(path: string): string[] {
    return path
      .split("/")
      .filter((segment) => segment.length > 0)
      .map(decodeURIComponent);
  }
}
