#!/bin/sh

set -e
#set -x

#########################
# Rights
#########################

# Make sure XWiki owns the passed directory
own_directory() {
  if [ ! 'xwiki' = `stat -c '%U' "$1"` ]; then
    chown -R xwiki:xwiki "$1"
  fi
}

# Make sure the passed directory exists and is owned by XWiki
prepare_directory() {
  if [ ! -d "$1" ]; then
    mkdir "$1"
  fi
  own_directory "$1"
}

# Create the xwiki user as defined in /usr/lib/sysusers.d/xwiki.conf
systemd-sysusers

# Make sure XWiki is able to write in the data directory
own_directory /var/lib/xwiki/data

# Make sure XWiki is able to write in the log, tmp and work directories
prepare_directory /var/log/xwiki
prepare_directory /var/lib/xwiki/tmp
prepare_directory /var/lib/xwiki/work

#########################
# Reload the service
#########################

# Enable the service if not yet enabled or update it
if deb-systemd-helper --quiet was-enabled 'xwiki.service'; then
    deb-systemd-helper enable 'xwiki.service' >/dev/null || true
else
    deb-systemd-helper update-state 'xwiki.service' >/dev/null || true
fi

# Need to reload systemd for the injected xwiki service configuration to be taken into account
systemctl daemon-reload
