// UK lang variables

tinyMCE.addToLang('',{
bold_desc : 'Bold (Ctrl+B)',
italic_desc : 'Italic (Ctrl+I)',
underline_desc : 'Underline (Ctrl+U)',
striketrough_desc : 'Strikethrough',
justifyleft_desc : 'Align left',
justifycenter_desc : 'Align center',
justifyright_desc : 'Align right',
justifyfull_desc : 'Align full',
bullist_desc : 'Unordered list',
numlist_desc : 'Ordered list',
outdent_desc : 'Outdent',
indent_desc : 'Indent',
undo_desc : 'Undo (Ctrl+Z)',
redo_desc : 'Redo (Ctrl+Y)',
link_desc : 'Insert/edit link',
unlink_desc : 'Unlink',
image_desc : 'Insert/edit image',
cleanup_desc : 'Cleanup messy code',
focus_alert : 'A editor instance must be focused before using this command.',
edit_confirm : 'Do you want to use the WYSIWYG mode for this textarea?',
insert_link_title : 'Insert/edit link',
link_wiki_tab : 'Wiki Page',
link_web_tab : 'Web Link',
link_attachments_tab : 'File Attachment',
link_file_tab : 'File Link',
link_email_tab : 'Email',
link_text_title : 'Text',
link_space_title : 'Space',
link_target_title: 'Target',
link_page_title : 'Link',
link_wiki_browse_tab : 'Browse',
link_wiki_search_tab : 'Search',
link_wiki_recent_viewed_tab : 'Recently Viewed',
link_wiki_recent_modified_tab : 'Recently Modified',        
link_attach_title : 'Attachment title',
link_attachment_title : 'Attachment name',
link_upload_attachment_title: 'Upload an attachment',
link_file_title : 'Link to',
link_file_warning_title : 'You can select a file on a shared drive on your computer. Make sure that the file is accessible <br/> to other user from the same path (drive letter or windows shared drive)<br/>',
link_email_title : 'Email Address',
insert : 'Insert',
update : 'Update',
cancel : 'Cancel',
insert_macro : 'Insert Macro',
loading_macros : 'Loading Macros .....',        
insert_link_target : 'Target',
insert_image_title : 'Insert/edit image',
insert_image_src : 'Image URL',
insert_image_alt : 'Image description',
help_desc : 'Help',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
