require(['jquery', 'bootstrap'], function($) {
  'use strict';
  
  $(document).ready(function() {
  
    // See Bootstrap's @screen-sm-min
    var smallScreenMinWidth = 768;
    // Enable the default menu action (navigation link) if the screen is not too small (horizontal menu).
    $('.navbar-nav a.dropdown-split-left').each(function() {
      $(this).click(function(event) {
        if ($(window).width() >= smallScreenMinWidth) {
          // Prevent the menu from opening.
          event.stopPropagation();
          // Follow the link only if this click event was not generated by the middle button.
          // See XWIKI-11725: Using mouse's middle click on actionmenu's items refreshes the current page
          if (event.button !== 1) {
            window.location = $(this).attr('href');
          }
        }
      });
    });

    // Fix the bad location of the dropdown menu when the trigger is close to the end of the screen.
    // See: http://jira.xwiki.org/browse/XWIKI-12609
    $(document).on('shown.bs.dropdown', function () {
      $('[aria-expanded="true"]').each( function() {
        var toggle    = $(this);
        var menu      = toggle.next('.dropdown-menu');
        var menuWidth = menu.outerWidth();
        // if the right corner of the menu is after the end of the screen
        if (menu.offset().left + menuWidth > $(document.body).outerWidth()) {
          // we put that corner at the same place than the toggle's right corner
          var newLocation = toggle.offset().left + toggle.outerWidth() - menuWidth;
          // but don't put it negative, or the user will have to scroll to the left!
          if (newLocation < 0) {
            newLocation = 0;
          }
          menu.offset({'left': newLocation});
        }
      });
    });
  
  });
});