/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.xwiki.display.internal;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.xwiki.bridge.DocumentModelBridge;
import org.xwiki.context.Execution;
import org.xwiki.context.ExecutionContext;
import org.xwiki.rendering.block.ImageBlock;
import org.xwiki.rendering.block.XDOM;
import org.xwiki.rendering.util.IdGenerator;
import org.xwiki.test.junit5.mockito.ComponentTest;
import org.xwiki.test.junit5.mockito.InjectMockComponents;
import org.xwiki.test.junit5.mockito.MockComponent;
import org.xwiki.velocity.VelocityEngine;
import org.xwiki.velocity.VelocityManager;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Unit tests for {@link DocumentContentAsyncExecutor}.
 *
 * @version $Id$
 */
@ComponentTest
class DocumentContentAsyncExecutorTest
{
    @InjectMockComponents
    private DocumentContentAsyncExecutor documentContentAsyncExecutor;

    @MockComponent
    private Execution execution;

    @MockComponent
    private VelocityManager velocityManager;

    @Mock
    private DocumentModelBridge document;

    private Map<Object, Object> xcontext = new HashMap<>();

    private DocumentDisplayerParameters parameters = new DocumentDisplayerParameters();

    @BeforeEach
    void beforeEach() throws Exception
    {
        ExecutionContext executionContext = new ExecutionContext();
        executionContext.setProperty("xwikicontext", this.xcontext);
        when(this.execution.getContext()).thenReturn(executionContext);

        VelocityEngine velocityEngine = mock(VelocityEngine.class);
        when(this.velocityManager.getVelocityEngine()).thenReturn(velocityEngine);
    }

    @Test
    void initializeAndExecuteAsync() throws Exception
    {
        IdGenerator idGenerator = new IdGenerator();
        // Simulate the fact that the id generator has already generated some ids.
        idGenerator.generateUniqueId("logo");
        this.parameters.setIdGenerator(idGenerator);

        ImageBlock image = new ImageBlock(null, true);
        // Use an id that was already generated by the id generator we're going to pass in the display parameters.
        image.setId("Ilogo");
        XDOM preparedXDOM = new XDOM(List.of(image));
        when(this.document.getPreparedXDOM()).thenReturn(preparedXDOM);

        this.documentContentAsyncExecutor.initialize("test", this.document, this.parameters);
        XDOM xdom = this.documentContentAsyncExecutor.execute(true);

        // Verify the returned XDOM is using the id generator provided in the display parameters.
        assertSame(idGenerator, xdom.getIdGenerator());

        // Verify the image id has been adapted.
        assertEquals("Ilogo-1", image.getId());
    }
}
