# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables standard Servlet handling.

[environment]
ee8

[depend]
server
sessions

[lib]
lib/jetty-servlet-api-4.0.6.jar
lib/jetty-ee8-nested-${jetty.version}.jar
lib/jetty-ee8-servlet-${jetty.version}.jar
