#!/bin/sh

set -e
#set -x

if [ ! -d /var/lib/xwiki/ ]; then
  mkdir /var/lib/xwiki/
fi
if [ ! -d /var/lib/xwiki/solr-data/ ]; then
  mkdir /var/lib/xwiki/solr-data/
fi

# TODO: add some automatic Solr data cleanup depending on the previous version

# Make the default solr user ("solr") owner of the data folder
if id "solr" >/dev/null 2>&1; then
  chown solr:solr -r /var/lib/xwiki/solr-data/
else
  echo "No user with name 'solr' could be found. Please make the user which runs Solr the owner of the folder /var/lib/xwiki/solr-data/"
fi
