#!/bin/sh

set -e
#set -x

#########################
# Restart Tomcat
#########################

invoke-rc.d --quiet tomcat8 restart || {
    RESULT=$?
    # Ignore if tomcat7 init script does not exist (yet)
    if [ $RESULT != 100 ]; then
    exit $RESULT
    fi
}
