/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.xwiki.yjs.websocket.internal;

import java.io.Serializable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.xwiki.user.UserReference;

/**
 * Represents a client connected to a room. A client is associated to a user and has an identifier generated by Yjs. An
 * user can have multiple clients connected to the same room.
 *
 * @version $Id$
 * @since 18.4.0RC1
 */
public class Client implements Serializable
{
    /**
     * The user associated to this client.
     */
    private final UserReference userReference;

    /**
     * The identifier of this client, generated by Yjs.
     */
    private Long id;

    /**
     * Creates a new client associated to the given user.
     * 
     * @param userReference the user associated to this client
     */
    public Client(UserReference userReference)
    {
        this.userReference = userReference;
    }

    /**
     * Creates a new client associated to the given user.
     * 
     * @param userReference the user associated to this client
     * @param id the identifier of this client, generated by Yjs
     */
    public Client(UserReference userReference, Long id)
    {
        this(userReference);
        this.id = id;
    }

    /**
     * Creates a new client by copying the user reference and identifier from another client.
     * 
     * @param other the client to copy
     */
    public Client(Client other)
    {
        this(other.userReference, other.id);
    }

    /**
     * @return the user associated to this client
     */
    public UserReference getUserReference()
    {
        return this.userReference;
    }

    /**
     * @return the identifier of this client, generated by Yjs
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * Sets the identifier of this client, generated by Yjs.
     * 
     * @param id the identifier of this client, generated by Yjs
     */
    public void setId(long id)
    {
        this.id = id;
    }

    @Override
    public boolean equals(Object obj)
    {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        Client other = (Client) obj;
        return new EqualsBuilder().append(this.id, other.id).append(this.userReference, other.userReference).isEquals();
    }

    @Override
    public int hashCode()
    {
        return new HashCodeBuilder(17, 37).append(this.id).append(this.userReference).toHashCode();
    }

    @Override
    public String toString()
    {
        return "Client{id=" + this.id + ", userReference=" + this.userReference + "}";
    }
}
